In [0]:
# Read S3 data
df = spark.read \
    .format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .option("fs.s3a.access.key", "YOUR_ACCESS_KEY_HERE") \
    .option("fs.s3a.secret.key", "YOUR_SECRET_KEY_HERE") \
    .option("fs.s3a.endpoint", "s3.amazonaws.com") \
    .load("s3a://nyc-taxi-trips-etl-pipeline/taxi_zone_lookup.csv")
    
df.show(5)

+----------+-------------+--------------------+------------+
|LocationID|      Borough|                Zone|service_zone|
+----------+-------------+--------------------+------------+
|         1|          EWR|      Newark Airport|         EWR|
|         2|       Queens|         Jamaica Bay|   Boro Zone|
|         3|        Bronx|Allerton/Pelham G...|   Boro Zone|
|         4|    Manhattan|       Alphabet City| Yellow Zone|
|         5|Staten Island|       Arden Heights|   Boro Zone|
+----------+-------------+--------------------+------------+
only showing top 5 rows

In [0]:
df.printSchema()

root
 |-- LocationID: integer (nullable = true)
 |-- Borough: string (nullable = true)
 |-- Zone: string (nullable = true)
 |-- service_zone: string (nullable = true)

In [0]:
df.describe().show()

+-------+---------------+-------+--------------------+------------+
|summary|     LocationID|Borough|                Zone|service_zone|
+-------+---------------+-------+--------------------+------------+
|  count|            265|    265|                 265|         265|
|   mean|          133.0|   NULL|                NULL|        NULL|
| stddev|76.643112323722|   NULL|                NULL|        NULL|
|    min|              1|  Bronx|Allerton/Pelham G...|    Airports|
|    max|            265|Unknown|      Yorkville West| Yellow Zone|
+-------+---------------+-------+--------------------+------------+

In [0]:
df_pd = df.toPandas()
df_pd

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      N/A          N/A
264         265            N/A           Outside of NYC          N/A

[265 rows x 4 columns]

In [0]:
df_pd.isnull()

     LocationID  Borough   Zone  service_zone
0         False    False  False         False
1         False    False  False         False
2         False    False  False         False
3         False    False  False         False
4         False    False  False         False
..          ...      ...    ...           ...
260       False    False  False         False
261       False    False  False         False
262       False    False  False         False
263       False    False  False         False
264       False    False  False         False

[265 rows x 4 columns]

In [0]:
df_pd.isnull().sum()

LocationID      0
Borough         0
Zone            0
service_zone    0
dtype: int64

In [0]:
df_pd.groupby("Borough")["Zone"].count()

Borough
Bronx            43
Brooklyn         61
EWR               1
Manhattan        69
N/A               1
Queens           69
Staten Island    20
Unknown           1
Name: Zone, dtype: int64

In [0]:
import pandas as pd
df_pd["Borough"]=df_pd["Borough"].replace(["N/A","Unknown"], pd.NA)
df_pd.dropna(subset=['Borough'],inplace=True)
df_pd

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
258         259          Bronx       Woodlawn/Wakefield    Boro Zone
259         260         Queens                 Woodside    Boro Zone
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone

[263 rows x 4 columns]

In [0]:
df_pd.groupby("Borough")["Zone"].count()

Borough
Bronx            43
Brooklyn         61
EWR               1
Manhattan        69
Queens           69
Staten Island    20
Name: Zone, dtype: int64

In [0]:
df_pd["is_yellow_zone"]=df_pd["service_zone"].apply(lambda x: "Yes" if x == "Yellow Zone" else "No")
df_pd["is_airport_zone"]=df_pd["Zone"].apply(lambda x: "Yes" if "airport" in x.lower() else "No")

def categorize(b):
    if b == "Manhattan": return "Core"
    elif b in ["Brooklyn", "Queens", "Bronx"]: return "Outer"
    else:
        return "Other"
df_pd["borough_category"] = df_pd["Borough"].apply(categorize)
df_pd.head(10)

   LocationID        Borough  ... is_airport_zone borough_category
0           1            EWR  ...             Yes            Other
1           2         Queens  ...              No            Outer
2           3          Bronx  ...              No            Outer
3           4      Manhattan  ...              No             Core
4           5  Staten Island  ...              No            Other
5           6  Staten Island  ...              No            Other
6           7         Queens  ...              No            Outer
7           8         Queens  ...              No            Outer
8           9         Queens  ...              No            Outer
9          10         Queens  ...              No            Outer

[10 rows x 7 columns]

In [0]:
summary = df_pd.groupby(['Borough',"service_zone"])["Zone"].count().reset_index()
summary.columns = ['Borough',"service_zone","zone_count"]
summary = summary.sort_values("zone_count", ascending=False)
summary

         Borough service_zone  zone_count
6         Queens    Boro Zone          67
1       Brooklyn    Boro Zone          61
4      Manhattan  Yellow Zone          55
0          Bronx    Boro Zone          43
7  Staten Island    Boro Zone          20
3      Manhattan    Boro Zone          14
5         Queens     Airports           2
2            EWR          EWR           1

In [0]:
df_spark_clean = spark.createDataFrame(df_pd)
df_spark_clean.write.format("delta").mode("overwrite").saveAsTable("taxi_zones")

In [0]:
%sql
Select * from taxi_zones;

LocationID,Borough,Zone,service_zone,is_yellow_zone,is_airport_zone,borough_category
1,EWR,Newark Airport,EWR,No,Yes,Other
2,Queens,Jamaica Bay,Boro Zone,No,No,Outer
3,Bronx,Allerton/Pelham Gardens,Boro Zone,No,No,Outer
4,Manhattan,Alphabet City,Yellow Zone,Yes,No,Core
5,Staten Island,Arden Heights,Boro Zone,No,No,Other
6,Staten Island,Arrochar/Fort Wadsworth,Boro Zone,No,No,Other
7,Queens,Astoria,Boro Zone,No,No,Outer
8,Queens,Astoria Park,Boro Zone,No,No,Outer
9,Queens,Auburndale,Boro Zone,No,No,Outer
10,Queens,Baisley Park,Boro Zone,No,No,Outer
11,Brooklyn,Bath Beach,Boro Zone,No,No,Outer
12,Manhattan,Battery Park,Yellow Zone,Yes,No,Core
13,Manhattan,Battery Park City,Yellow Zone,Yes,No,Core
14,Brooklyn,Bay Ridge,Boro Zone,No,No,Outer
15,Queens,Bay Terrace/Fort Totten,Boro Zone,No,No,Outer
16,Queens,Bayside,Boro Zone,No,No,Outer
17,Brooklyn,Bedford,Boro Zone,No,No,Outer
18,Bronx,Bedford Park,Boro Zone,No,No,Outer
19,Queens,Bellerose,Boro Zone,No,No,Outer
20,Bronx,Belmont,Boro Zone,No,No,Outer
21,Brooklyn,Bensonhurst East,Boro Zone,No,No,Outer
22,Brooklyn,Bensonhurst West,Boro Zone,No,No,Outer
23,Staten Island,Bloomfield/Emerson Hill,Boro Zone,No,No,Other
24,Manhattan,Bloomingdale,Yellow Zone,Yes,No,Core
25,Brooklyn,Boerum Hill,Boro Zone,No,No,Outer
26,Brooklyn,Borough Park,Boro Zone,No,No,Outer
27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone,No,No,Outer
28,Queens,Briarwood/Jamaica Hills,Boro Zone,No,No,Outer
29,Brooklyn,Brighton Beach,Boro Zone,No,No,Outer
30,Queens,Broad Channel,Boro Zone,No,No,Outer
31,Bronx,Bronx Park,Boro Zone,No,No,Outer
32,Bronx,Bronxdale,Boro Zone,No,No,Outer
33,Brooklyn,Brooklyn Heights,Boro Zone,No,No,Outer
34,Brooklyn,Brooklyn Navy Yard,Boro Zone,No,No,Outer
35,Brooklyn,Brownsville,Boro Zone,No,No,Outer
36,Brooklyn,Bushwick North,Boro Zone,No,No,Outer
37,Brooklyn,Bushwick South,Boro Zone,No,No,Outer
38,Queens,Cambria Heights,Boro Zone,No,No,Outer
39,Brooklyn,Canarsie,Boro Zone,No,No,Outer
40,Brooklyn,Carroll Gardens,Boro Zone,No,No,Outer
41,Manhattan,Central Harlem,Boro Zone,No,No,Core
42,Manhattan,Central Harlem North,Boro Zone,No,No,Core
43,Manhattan,Central Park,Yellow Zone,Yes,No,Core
44,Staten Island,Charleston/Tottenville,Boro Zone,No,No,Other
45,Manhattan,Chinatown,Yellow Zone,Yes,No,Core
46,Bronx,City Island,Boro Zone,No,No,Outer
47,Bronx,Claremont/Bathgate,Boro Zone,No,No,Outer
48,Manhattan,Clinton East,Yellow Zone,Yes,No,Core
49,Brooklyn,Clinton Hill,Boro Zone,No,No,Outer
50,Manhattan,Clinton West,Yellow Zone,Yes,No,Core
51,Bronx,Co-Op City,Boro Zone,No,No,Outer
52,Brooklyn,Cobble Hill,Boro Zone,No,No,Outer
53,Queens,College Point,Boro Zone,No,No,Outer
54,Brooklyn,Columbia Street,Boro Zone,No,No,Outer
55,Brooklyn,Coney Island,Boro Zone,No,No,Outer
56,Queens,Corona,Boro Zone,No,No,Outer
57,Queens,Corona,Boro Zone,No,No,Outer
58,Bronx,Country Club,Boro Zone,No,No,Outer
59,Bronx,Crotona Park,Boro Zone,No,No,Outer
60,Bronx,Crotona Park East,Boro Zone,No,No,Outer
61,Brooklyn,Crown Heights North,Boro Zone,No,No,Outer
62,Brooklyn,Crown Heights South,Boro Zone,No,No,Outer
63,Brooklyn,Cypress Hills,Boro Zone,No,No,Outer
64,Queens,Douglaston,Boro Zone,No,No,Outer
65,Brooklyn,Downtown Brooklyn/MetroTech,Boro Zone,No,No,Outer
66,Brooklyn,DUMBO/Vinegar Hill,Boro Zone,No,No,Outer
67,Brooklyn,Dyker Heights,Boro Zone,No,No,Outer
68,Manhattan,East Chelsea,Yellow Zone,Yes,No,Core
69,Bronx,East Concourse/Concourse Village,Boro Zone,No,No,Outer
70,Queens,East Elmhurst,Boro Zone,No,No,Outer
71,Brooklyn,East Flatbush/Farragut,Boro Zone,No,No,Outer
72,Brooklyn,East Flatbush/Remsen Village,Boro Zone,No,No,Outer
73,Queens,East Flushing,Boro Zone,No,No,Outer
74,Manhattan,East Harlem North,Boro Zone,No,No,Core
75,Manhattan,East Harlem South,Boro Zone,No,No,Core
76,Brooklyn,East New York,Boro Zone,No,No,Outer
77,Brooklyn,East New York/Pennsylvania Avenue,Boro Zone,No,No,Outer
78,Bronx,East Tremont,Boro Zone,No,No,Outer
79,Manhattan,East Village,Yellow Zone,Yes,No,Core
80,Brooklyn,East Williamsburg,Boro Zone,No,No,Outer
81,Bronx,Eastchester,Boro Zone,No,No,Outer
82,Queens,Elmhurst,Boro Zone,No,No,Outer
83,Queens,Elmhurst/Maspeth,Boro Zone,No,No,Outer
84,Staten Island,Eltingville/Annadale/Prince's Bay,Boro Zone,No,No,Other
85,Brooklyn,Erasmus,Boro Zone,No,No,Outer
86,Queens,Far Rockaway,Boro Zone,No,No,Outer
87,Manhattan,Financial District North,Yellow Zone,Yes,No,Core
88,Manhattan,Financial District South,Yellow Zone,Yes,No,Core
89,Brooklyn,Flatbush/Ditmas Park,Boro Zone,No,No,Outer
90,Manhattan,Flatiron,Yellow Zone,Yes,No,Core
91,Brooklyn,Flatlands,Boro Zone,No,No,Outer
92,Queens,Flushing,Boro Zone,No,No,Outer
93,Queens,Flushing Meadows-Corona Park,Boro Zone,No,No,Outer
94,Bronx,Fordham South,Boro Zone,No,No,Outer
95,Queens,Forest Hills,Boro Zone,No,No,Outer
96,Queens,Forest Park/Highland Park,Boro Zone,No,No,Outer
97,Brooklyn,Fort Greene,Boro Zone,No,No,Outer
98,Queens,Fresh Meadows,Boro Zone,No,No,Outer
99,Staten Island,Freshkills Park,Boro Zone,No,No,Other
100,Manhattan,Garment District,Yellow Zone,Yes,No,Core
101,Queens,Glen Oaks,Boro Zone,No,No,Outer
102,Queens,Glendale,Boro Zone,No,No,Outer
103,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,Yes,No,Core
104,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,Yes,No,Core
105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone,Yes,No,Core
106,Brooklyn,Gowanus,Boro Zone,No,No,Outer
107,Manhattan,Gramercy,Yellow Zone,Yes,No,Core
108,Brooklyn,Gravesend,Boro Zone,No,No,Outer
109,Staten Island,Great Kills,Boro Zone,No,No,Other
110,Staten Island,Great Kills Park,Boro Zone,No,No,Other
111,Brooklyn,Green-Wood Cemetery,Boro Zone,No,No,Outer
112,Brooklyn,Greenpoint,Boro Zone,No,No,Outer
113,Manhattan,Greenwich Village North,Yellow Zone,Yes,No,Core
114,Manhattan,Greenwich Village South,Yellow Zone,Yes,No,Core
115,Staten Island,Grymes Hill/Clifton,Boro Zone,No,No,Other
116,Manhattan,Hamilton Heights,Boro Zone,No,No,Core
117,Queens,Hammels/Arverne,Boro Zone,No,No,Outer
118,Staten Island,Heartland Village/Todt Hill,Boro Zone,No,No,Other
119,Bronx,Highbridge,Boro Zone,No,No,Outer
120,Manhattan,Highbridge Park,Boro Zone,No,No,Core
121,Queens,Hillcrest/Pomonok,Boro Zone,No,No,Outer
122,Queens,Hollis,Boro Zone,No,No,Outer
123,Brooklyn,Homecrest,Boro Zone,No,No,Outer
124,Queens,Howard Beach,Boro Zone,No,No,Outer
125,Manhattan,Hudson Sq,Yellow Zone,Yes,No,Core
126,Bronx,Hunts Point,Boro Zone,No,No,Outer
127,Manhattan,Inwood,Boro Zone,No,No,Core
128,Manhattan,Inwood Hill Park,Boro Zone,No,No,Core
129,Queens,Jackson Heights,Boro Zone,No,No,Outer
130,Queens,Jamaica,Boro Zone,No,No,Outer
131,Queens,Jamaica Estates,Boro Zone,No,No,Outer
132,Queens,JFK Airport,Airports,No,Yes,Outer
133,Brooklyn,Kensington,Boro Zone,No,No,Outer
134,Queens,Kew Gardens,Boro Zone,No,No,Outer
135,Queens,Kew Gardens Hills,Boro Zone,No,No,Outer
136,Bronx,Kingsbridge Heights,Boro Zone,No,No,Outer
137,Manhattan,Kips Bay,Yellow Zone,Yes,No,Core
138,Queens,LaGuardia Airport,Airports,No,Yes,Outer
139,Queens,Laurelton,Boro Zone,No,No,Outer
140,Manhattan,Lenox Hill East,Yellow Zone,Yes,No,Core
141,Manhattan,Lenox Hill West,Yellow Zone,Yes,No,Core
142,Manhattan,Lincoln Square East,Yellow Zone,Yes,No,Core
143,Manhattan,Lincoln Square West,Yellow Zone,Yes,No,Core
144,Manhattan,Little Italy/NoLiTa,Yellow Zone,Yes,No,Core
145,Queens,Long Island City/Hunters Point,Boro Zone,No,No,Outer
146,Queens,Long Island City/Queens Plaza,Boro Zone,No,No,Outer
147,Bronx,Longwood,Boro Zone,No,No,Outer
148,Manhattan,Lower East Side,Yellow Zone,Yes,No,Core
149,Brooklyn,Madison,Boro Zone,No,No,Outer
150,Brooklyn,Manhattan Beach,Boro Zone,No,No,Outer
151,Manhattan,Manhattan Valley,Yellow Zone,Yes,No,Core
152,Manhattan,Manhattanville,Boro Zone,No,No,Core
153,Manhattan,Marble Hill,Boro Zone,No,No,Core
154,Brooklyn,Marine Park/Floyd Bennett Field,Boro Zone,No,No,Outer
155,Brooklyn,Marine Park/Mill Basin,Boro Zone,No,No,Outer
156,Staten Island,Mariners Harbor,Boro Zone,No,No,Other
157,Queens,Maspeth,Boro Zone,No,No,Outer
158,Manhattan,Meatpacking/West Village West,Yellow Zone,Yes,No,Core
159,Bronx,Melrose South,Boro Zone,No,No,Outer
160,Queens,Middle Village,Boro Zone,No,No,Outer
161,Manhattan,Midtown Center,Yellow Zone,Yes,No,Core
162,Manhattan,Midtown East,Yellow Zone,Yes,No,Core
163,Manhattan,Midtown North,Yellow Zone,Yes,No,Core
164,Manhattan,Midtown South,Yellow Zone,Yes,No,Core
165,Brooklyn,Midwood,Boro Zone,No,No,Outer
166,Manhattan,Morningside Heights,Boro Zone,No,No,Core
167,Bronx,Morrisania/Melrose,Boro Zone,No,No,Outer
168,Bronx,Mott Haven/Port Morris,Boro Zone,No,No,Outer
169,Bronx,Mount Hope,Boro Zone,No,No,Outer
170,Manhattan,Murray Hill,Yellow Zone,Yes,No,Core
171,Queens,Murray Hill-Queens,Boro Zone,No,No,Outer
172,Staten Island,New Dorp/Midland Beach,Boro Zone,No,No,Other
173,Queens,North Corona,Boro Zone,No,No,Outer
174,Bronx,Norwood,Boro Zone,No,No,Outer
175,Queens,Oakland Gardens,Boro Zone,No,No,Outer
176,Staten Island,Oakwood,Boro Zone,No,No,Other
177,Brooklyn,Ocean Hill,Boro Zone,No,No,Outer
178,Brooklyn,Ocean Parkway South,Boro Zone,No,No,Outer
179,Queens,Old Astoria,Boro Zone,No,No,Outer
180,Queens,Ozone Park,Boro Zone,No,No,Outer
181,Brooklyn,Park Slope,Boro Zone,No,No,Outer
182,Bronx,Parkchester,Boro Zone,No,No,Outer
183,Bronx,Pelham Bay,Boro Zone,No,No,Outer
184,Bronx,Pelham Bay Park,Boro Zone,No,No,Outer
185,Bronx,Pelham Parkway,Boro Zone,No,No,Outer
186,Manhattan,Penn Station/Madison Sq West,Yellow Zone,Yes,No,Core
187,Staten Island,Port Richmond,Boro Zone,No,No,Other
188,Brooklyn,Prospect-Lefferts Gardens,Boro Zone,No,No,Outer
189,Brooklyn,Prospect Heights,Boro Zone,No,No,Outer
190,Brooklyn,Prospect Park,Boro Zone,No,No,Outer
191,Queens,Queens Village,Boro Zone,No,No,Outer
192,Queens,Queensboro Hill,Boro Zone,No,No,Outer
193,Queens,Queensbridge/Ravenswood,Boro Zone,No,No,Outer
194,Manhattan,Randalls Island,Yellow Zone,Yes,No,Core
195,Brooklyn,Red Hook,Boro Zone,No,No,Outer
196,Queens,Rego Park,Boro Zone,No,No,Outer
197,Queens,Richmond Hill,Boro Zone,No,No,Outer
198,Queens,Ridgewood,Boro Zone,No,No,Outer
199,Bronx,Rikers Island,Boro Zone,No,No,Outer
200,Bronx,Riverdale/North Riverdale/Fieldston,Boro Zone,No,No,Outer
201,Queens,Rockaway Park,Boro Zone,No,No,Outer
202,Manhattan,Roosevelt Island,Boro Zone,No,No,Core
203,Queens,Rosedale,Boro Zone,No,No,Outer
204,Staten Island,Rossville/Woodrow,Boro Zone,No,No,Other
205,Queens,Saint Albans,Boro Zone,No,No,Outer
206,Staten Island,Saint George/New Brighton,Boro Zone,No,No,Other
207,Queens,Saint Michaels Cemetery/Woodside,Boro Zone,No,No,Outer
208,Bronx,Schuylerville/Edgewater Park,Boro Zone,No,No,Outer
209,Manhattan,Seaport,Yellow Zone,Yes,No,Core
210,Brooklyn,Sheepshead Bay,Boro Zone,No,No,Outer
211,Manhattan,SoHo,Yellow Zone,Yes,No,Core
212,Bronx,Soundview/Bruckner,Boro Zone,No,No,Outer
213,Bronx,Soundview/Castle Hill,Boro Zone,No,No,Outer
214,Staten Island,South Beach/Dongan Hills,Boro Zone,No,No,Other
215,Queens,South Jamaica,Boro Zone,No,No,Outer
216,Queens,South Ozone Park,Boro Zone,No,No,Outer
217,Brooklyn,South Williamsburg,Boro Zone,No,No,Outer
218,Queens,Springfield Gardens North,Boro Zone,No,No,Outer
219,Queens,Springfield Gardens South,Boro Zone,No,No,Outer
220,Bronx,Spuyten Duyvil/Kingsbridge,Boro Zone,No,No,Outer
221,Staten Island,Stapleton,Boro Zone,No,No,Other
222,Brooklyn,Starrett City,Boro Zone,No,No,Outer
223,Queens,Steinway,Boro Zone,No,No,Outer
224,Manhattan,Stuy Town/Peter Cooper Village,Yellow Zone,Yes,No,Core
225,Brooklyn,Stuyvesant Heights,Boro Zone,No,No,Outer
226,Queens,Sunnyside,Boro Zone,No,No,Outer
227,Brooklyn,Sunset Park East,Boro Zone,No,No,Outer
228,Brooklyn,Sunset Park West,Boro Zone,No,No,Outer
229,Manhattan,Sutton Place/Turtle Bay North,Yellow Zone,Yes,No,Core
230,Manhattan,Times Sq/Theatre District,Yellow Zone,Yes,No,Core
231,Manhattan,TriBeCa/Civic Center,Yellow Zone,Yes,No,Core
232,Manhattan,Two Bridges/Seward Park,Yellow Zone,Yes,No,Core
233,Manhattan,UN/Turtle Bay South,Yellow Zone,Yes,No,Core
234,Manhattan,Union Sq,Yellow Zone,Yes,No,Core
235,Bronx,University Heights/Morris Heights,Boro Zone,No,No,Outer
236,Manhattan,Upper East Side North,Yellow Zone,Yes,No,Core
237,Manhattan,Upper East Side South,Yellow Zone,Yes,No,Core
238,Manhattan,Upper West Side North,Yellow Zone,Yes,No,Core
239,Manhattan,Upper West Side South,Yellow Zone,Yes,No,Core
240,Bronx,Van Cortlandt Park,Boro Zone,No,No,Outer
241,Bronx,Van Cortlandt Village,Boro Zone,No,No,Outer
242,Bronx,Van Nest/Morris Park,Boro Zone,No,No,Outer
243,Manhattan,Washington Heights North,Boro Zone,No,No,Core
244,Manhattan,Washington Heights South,Boro Zone,No,No,Core
245,Staten Island,West Brighton,Boro Zone,No,No,Other
246,Manhattan,West Chelsea/Hudson Yards,Yellow Zone,Yes,No,Core
247,Bronx,West Concourse,Boro Zone,No,No,Outer
248,Bronx,West Farms/Bronx River,Boro Zone,No,No,Outer
249,Manhattan,West Village,Yellow Zone,Yes,No,Core
250,Bronx,Westchester Village/Unionport,Boro Zone,No,No,Outer
251,Staten Island,Westerleigh,Boro Zone,No,No,Other
252,Queens,Whitestone,Boro Zone,No,No,Outer
253,Queens,Willets Point,Boro Zone,No,No,Outer
254,Bronx,Williamsbridge/Olinville,Boro Zone,No,No,Outer
255,Brooklyn,Williamsburg (North Side),Boro Zone,No,No,Outer
256,Brooklyn,Williamsburg (South Side),Boro Zone,No,No,Outer
257,Brooklyn,Windsor Terrace,Boro Zone,No,No,Outer
258,Queens,Woodhaven,Boro Zone,No,No,Outer
259,Bronx,Woodlawn/Wakefield,Boro Zone,No,No,Outer
260,Queens,Woodside,Boro Zone,No,No,Outer
261,Manhattan,World Trade Center,Yellow Zone,Yes,No,Core
262,Manhattan,Yorkville East,Yellow Zone,Yes,No,Core
263,Manhattan,Yorkville West,Yellow Zone,Yes,No,Core